### ISSUE TITLE
nord not on melpa or any other repository

### ISSUE THREAD

**Issue by gregf** [arcticicestudio/nord-emacs#20]
I can't seem to find the nord theme on any of the listed repositories listed below.

**Comment by arcticicestudio** [comment]
Thanks for your notification 👍 
It will be available as soon as [melpa/melpa PR #4655](https://github.com/melpa/melpa/pull/4655) is mergeable also described in the backlog issue comment [arcticicestudio/nord #6](https://github.com/arcticicestudio/nord/issues/6#issuecomment-289239005) posted yesterday.
One of the Melpa maintainers reviewed the package and created PR #21 to fix some format issues which I'll need to review and merge to make Nord Emacs available from MELPA as soon as possible.

**Comment by arcticicestudio** [comment]
The PR has been merged and [nord-theme](https://melpa.org/#/nord-theme) is now available from MELPA.
