### ISSUE TITLE
Comments are hard to read

### ISSUE THREAD

**Issue by jcinnamond** [arcticicestudio/nord-emacs#23]
Nord is lovely, but I'm finding it hard to read comments with them set to nord3:

![nord3](https://cloud.githubusercontent.com/assets/27396/24580911/0a4834ca-1709-11e7-93c8-adac18eb415a.png)

What do you think about changing it to nord9? I can create a PR with the change if you're happy with it, but if everyone prefers the de-emphasized current scheme then I'll just change my local copy:

![nord9](https://cloud.githubusercontent.com/assets/27396/24580927/65ba0f9a-1709-11e7-945f-a3320d9eabae.png)

**Comment by arcticicestudio** [comment]
Thanks for your report and nice to see you like it 👍 

It looks like there are general color problems since the background it definitely not part of the Nord color palette. The color of the code also looks strange except the comments which are colored correct. but are hard to read related to the background color.

I'm not a Windows user so you may need to help me out there.
  - Is Emacs running in terminal- or GUI mode? If it run in terminal mode make sure to set up your terminal emulator as described in the README [installation](https://github.com/arcticicestudio/nord-emacs#installation) section to make the Nord colors available for the terminal.
  - Can you post a list of your installed Emacs packages so I can try to reproduce it? (I've create some VirtualBox container with Windows 7 and Windows 10 for several other Nord port projects 😄 )

**Comment by mandarvaze** [comment]
I just installed this on macOS
Lovely theme.

But I too have same problem - comments are hard to read (python, if it matters)

**Comment by jcinnamond** [comment]
Thanks for replying to this @arcticicestudio. You're right about the background - I had an entry in my .emacs file from `customize` that was overriding the theme. I've removed that so I now have the proper nord background. I still think that comments are hard to read. It's particularly bad if you highlight a region. Here is the same file with the correct background color and a region highlighted:

![nord](https://cloud.githubusercontent.com/assets/27396/24709611/5d385758-1a12-11e7-983e-4deffacad23d.png)

**Comment by arcticicestudio** [comment]
@mandarvaze  The low contrast for comments has been selected specifically to not disturb code flow and keep the focus of the developer on the code. Using other colors for it like e.g. `nord7` would completely mix the separation between the code and comments. `nord7` is used for classes/types/interfaces/documentation tags and you would be unable to differ if it is part of the running code or just a comment.

@jcinnamond Unfortunately this is related to the fact that it is not possible to use alpha channel values for opacity so Nord Emacs can only make use of the Nord colors.
You may change it to `nord6`, but this would make it hard to read code which is colorized with the default foreground `nord4`.
The current selection color is the only color which does not collidate with any code color, it only make comments a little bit harder to read 😮 

It is totally fine that users do not agree to all highlighting color assignments, everyone has different preferences. That is the reason why themes exist 😉 

If you'd like to change individual parts of the theme and you don't have to change it in the theme file itself, which would be overriden each time you update your packages.
I'm not a Emac user, but I know from Vim that you can define custom color definitions as soon as a specific theme gets loaded. Maybe you know a better way, but it should work if you override definitions you like to change by adding it to `
(custom-set-faces` in your `~/.emacs.d¸init.el`

**Comment by jcinnamond** [comment]
Thanks again @arcticicestudio for replying to this and for the great work with Nord. I'll stick to overriding it in my local config.

**Comment by mandarvaze** [comment]
@jcinnamond Can you share your local config details ? It would be helpful to those that need it.

**Comment by jcinnamond** [comment]
@mandarvaze my full config is here: https://github.com/jcinnamond/emacs

The pertinent bits are:

```
  (load-theme 'nord t)
  (set-face-attribute 'font-lock-comment-face nil
                      :foreground "#81A1C1") ; nord9
  (set-face-attribute 'vertical-border nil
                      :foreground "#EBCB8B") ; nord13
```

**Comment by arcticicestudio** [comment]
I've posted [this comment](https://github.com/arcticicestudio/nord-emacs/issues/32#issuecomment-299646111) in #32 which is related to this issue.
