### ISSUE TITLE
Mode line in inactive windows is nearly invisible

### ISSUE THREAD

**Issue by cavd** [arcticicestudio/nord-emacs#25]
When there are multiple windows, it is nearly impossible to see the (e.g.) buffer name of inactive windows.

**Comment by arcticicestudio** [comment]
The inactive modeline has been designed to be colored with the base background color `nord0` and only the active window modeline should be colored with `nord2` to make it easy to see which window is active.
Normally only the background should be changed and texts should be readable.

Can you post a screenshot please so I can see whats going on there?
Also please post a list of all emacs packages you've installed which modify the modeline (including themes) so I can try to reproduce it.

**Comment by stardiviner** [comment]
The inactive mode-line face does need to be more distinct.

**Comment by cavd** [comment]
Here is a screenshot with Emacs started with -Q, then loading nord-theme:
<img width="1099" alt="screenshot 2017-04-03 at 6 03 09 pm" src="https://cloud.githubusercontent.com/assets/261342/24651379/3485b3f2-18f3-11e7-8d3e-2ecc63077896.png">

The inactive window is on the left.

**Comment by cavd** [comment]
For comparison's sake, here is a similar layout with the vim nord theme:
![vim-nord](https://cloud.githubusercontent.com/assets/261342/24711152/c0f5fc88-19e4-11e7-9fca-87731c47582d.png)

**Comment by arcticicestudio** [comment]
I've changed the `foreground` for inactive `mode-line`s to `nord4`.
You can test the changes in 🌱 [improvement/ghi-#25-mode-line-in-inactive-windows-is-nearly-invisible](https://github.com/arcticicestudio/nord-emacs/tree/improvement/ghi-%2325-mode-line-in-inactive-windows-is-nearly-invisible)

**Comment by cavd** [comment]
Looks good to me.

**Comment by arcticicestudio** [comment]
🚢 Shipped with MELPA package release version 🏷 [0.2.0](https://github.com/arcticicestudio/nord-emacs/releases/tag/v0.2.0).
