### ISSUE TITLE
The underline of text is not very distinct

### ISSUE THREAD

**Issue by stardiviner** [arcticicestudio/nord-emacs#26]
Can you make the underline of text to be more distinct like bold face ?

**Comment by arcticicestudio** [comment]
Can you explain this in detail?
Do you mean to change the weight (height) of it so the line is thicker?

**Comment by stardiviner** [comment]
I mean the underline line color should be more distinct.

**Comment by arcticicestudio** [comment]
Normally the line should adapt the color of the word. The fallback color is set to the default text color `nord4` which should be recognizable in most cases.

It is totally fine if you do not agree to all highlighting color assignments, everyone has different preferences. That is the reason why themes exist 😉 
If you like to use another default color you can override the face in your `~/.emacs.d/init.el`.

**Comment by stardiviner** [comment]
I see, thanks.
