### ISSUE TITLE
which-function-mode support

### ISSUE THREAD

**Issue by microamp** [arcticicestudio/nord-emacs#28]
Currently,

![screen shot 2017-04-05 at 7 48 11 am](https://cloud.githubusercontent.com/assets/1378791/24675712/51d64a2a-19d4-11e7-9504-476571209756.png)

**Comment by arcticicestudio** [comment]
<p align="center"><strong>Before</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/24758354/6ed3c51c-1ae2-11e7-8a18-b58c1d0e6185.png"/><br><strong>After</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/24758374/7bc489aa-1ae2-11e7-9eba-6657425a3936.png"/></p>

**Comment by arcticicestudio** [comment]
🚢 Shipped with MELPA package release version 🏷 [0.2.0](https://github.com/arcticicestudio/nord-emacs/releases/tag/v0.2.0).
