### ISSUE TITLE
region background color is same with hl-line

### ISSUE THREAD

**Issue by stardiviner** [arcticicestudio/nord-emacs#29]
Because `region` face background color is same with `hl-line` face background. So when region select a string in current line has no distinct color. Hope you can improve this.

**Comment by arcticicestudio** [comment]
Can you post a screenshot of the problem?
Both groups should not disturb each other since `region` uses `nord1` and `hl-line` uses `nord2`.

Have you checked if you've set color rules which override specific groups of the theme?

**Comment by stardiviner** [comment]
Now seems solved. Days ago it is same color, maybe my config issue. Thanks.

**Comment by localredhead** [comment]
I have the same problem with the default theme - they may be slightly different colors but I cannot tell on my macbook pro.
