### ISSUE TITLE
Active and inactive modelines are hard to distinguish, as well as region highlight.

### ISSUE THREAD

**Issue by localredhead** [arcticicestudio/nord-emacs#32]
I have to squint on these two items., otherwise this is a perfect theme.

1.  I can barely tell what is selected in the region 
1.  It is hard for me to distinguish between modelines.

Is this the right amount of contrast for the theme?  
<img width="842" alt="screen shot 2017-04-25 at 3 29 46 pm" src="https://cloud.githubusercontent.com/assets/152448/25410547/5233acbc-29cc-11e7-9f45-84531fa78e81.png">

**Comment by arcticicestudio** [comment]
It is not easy to implement this when the theme engine is limited to pure HEX values. In other port projects it is possible to improve this by using transparency or advanced theming features like CSS.
Maybe I'll implement a theme setting which allows to percentage increase the comment color like the one in the [Nord Atom UI](https://github.com/arcticicestudio/nord-atom-syntax/pull/47).

**Comment by localredhead** [comment]
For what its worth, I think a simple solution would be to invert the color on the inactive modeline, and use the current inactive color for a boxed edge and text.  IMO that would solve it nicely.

I did have a version like this that I can try and submit as a PR somewhere...  I did tinker a bit with it.

**Comment by arcticicestudio** [comment]
@localredhead I've implemented two theme customization

*  for different region highlight styles in #46
* for uniform mode lines in #48

Feel free to check out and post some feedback.
