### ISSUE TITLE
Python docstrings are very pale

### ISSUE THREAD

**Issue by cryptomaniac512** [arcticicestudio/nord-emacs#51]
Docstrings in python are not readable if not to establish illumination of the display on a limit. Is it possible to make it a little more noticeable?
![image](https://user-images.githubusercontent.com/10251687/31350388-4c860d6a-ad6a-11e7-9e60-bb2bf9ce905c.png)

**Comment by arcticicestudio** [comment]
There's a [theme customization to define a custom comment brightness](https://github.com/arcticicestudio/nord-emacs/issues/43) which has been implemented and merged in #44. It will be available with version [0.4.0](https://github.com/arcticicestudio/nord-emacs/projects/8). I try to prepare and release it by the end of the week.

**Comment by cryptomaniac512** [comment]
Looks good! Thank you!
