### ISSUE TITLE
Support polymode

### ISSUE THREAD

**Issue by basille** [arcticicestudio/nord-emacs#53]
Thanks for this wonderful theme, very relaxing!

Do you have any plan to support [polymode](https://github.com/vspinu/polymode)? Polymode allows to have multiple major modes in the same buffer, as a series of chunks from one mode or the other. It can be very useful for Org files, or Markdown files with YAML headers, or any combination using R (RMarkdown, R knitr, etc.). As it is now, "embedded" chunks are on a very light background, which makes them almost impossible to read. See for instance, a very simple example of RMarkdown (i.e. R chunks in a Markdown file):

![screenshot from 2017-11-13 15-25-27](https://user-images.githubusercontent.com/4000337/32747816-f6293fbc-c887-11e7-9100-d45c82bb90d0.png)

The light background should ideally be gray, just a bit lighter than the normal gray background so that it's noticeable.
I'd be happy to help figuring it out, but I'm not exactly sure where to start (I have no knowledge of theming or the mechanisms of faces in Emacs).

**Comment by arcticicestudio** [comment]
Glad to see you like the theme :smile: 

If you'd like to try it on your own and submit a PR you can add this function and the matching key mapping to your `init.el`:

```lisp
; Shows the face at the current cursor position.
(defun wface (pos)
  (interactive "d")
  (let ((face (or (get-char-property (point) 'read-face-name)
                  (get-char-property (point) 'face))))
    (if face (message "Face: %s" face) (message "No face at %d" pos))))
```

```lisp
; Set a global key mapping for the wface function
(global-set-key (kbd "C-x C-w") 'wface)
```

Pressing <kbd>Ctrl</kbd>+<kbd>x</kbd> followed by <kbd>Ctrl</kbd>+<kbd>w</kbd> will show the face at the cursor position.

You can also show all used faces in the current buffer via `list-faces-display`.

**Comment by basille** [comment]
Sorry it took me so long to come back to this issue… because it actually magically solved! It took me a while to figure out what happened. Here is what I have now:

![screenshot from 2017-11-22 22-57-14](https://user-images.githubusercontent.com/4000337/33158528-a12d280e-cfd8-11e7-83cb-ed2c2191fa6f.png)

… which is just perfect. If I understand it correctly, it turns out that it may come from the `theme-changer` package, which automatically changes themes depending on the time of the day, but wasn't obviously changing all face properties correctly. So what I had before was actually not a vanilla `nord` theme, but `nord` with bits of `apropospriate-light`. 

In the end, what I thought was a problem with `nord` is actually a problem with `theme-changer` (I think). Issue closed!

**Comment by arcticicestudio** [comment]
Alright, thanks for the feedback :+1:
