### ISSUE TITLE
left margin matches left char with global-linum-mode

### ISSUE THREAD

**Issue by dylnmc** [arcticicestudio/nord-emacs#56]
![emacs](https://user-images.githubusercontent.com/7635158/34455539-1957aa32-ed4f-11e7-9ee4-de9774ed84b9.png)

When there is a button flushed left and `global-linum-mode` is enabled, the button extends into the left margin (where the linums exist).

The theme `leuven` has the same problem. Most of the other themes I have seen do not try to do this.

Is this something that the theme should turn off? I couldn't find what setting it would be...

Thanks

**Comment by arcticicestudio** [comment]
Try to set `(setq linum-format "%d ")` in your config which allows to define the formatting of the line number. it documented for `linum` in the chapter about [separating line numbers from text][ref].

I think this config should not be handled by any theme, each users might like to format the gutter to fit their needs, but the underline and button border which are also rendering in the gutter seem to be misplaced there.

[ref]: https://www.emacswiki.org/emacs/LineNumbers#toc8

**Comment by dylnmc** [comment]
doesn't work for me

**Comment by dylnmc** [comment]
I don't know what is wrong with emacs. I am just not going to use linum-mode … Very strange. :confused:

**Comment by dylnmc** [comment]
Under `custom-set-faces`, I have put:

```elisp
(linum ((t (:stipple nil :background "#2E3440" :foreground "#4C566A" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal)))))
```

(in reality, I just used `M-x customize` search \~`Linum`\~> `Linum faces` ~~> disable all face attributes. Looks fine now (`Revert` button still a little weird):

![screenshot from 2017-12-31 11-58-55](https://user-images.githubusercontent.com/7635158/34463190-2589ce10-ee22-11e7-820b-cfca09ef3498.png)

Closing because not issue with theme (unless you want to disable all of those face attributes for linum faces, but I'd assume not).
