### ISSUE TITLE
Add a light variant

### ISSUE THREAD

**Issue by To1ne** [arcticicestudio/nord-emacs#72]
Wow, this theme is gorgeous and well executed. Excellent work!

But have you considered a light variant (light background) of this theme?

**Comment by arcticicestudio** [comment]
Hi @To1ne 👋 , thanks for your contribution 👍 

There's arcticicestudio/nord#46 that documents the plan for a light theme that'll be implemented for all port projects, but there are currently more urgent tasks like the transition of docs and assets to the [new official Nord website](https://www.nordtheme.com).
There are also some links by users who also already created light themes for ports like Emacs, maybe there's a fork you'd like to use until an official light mode is available.

**Comment by To1ne** [comment]
Thanks for the swift reply. That's awesome. I'm looking forward to see the light theme happen.

Feel free to close this issue and use https://github.com/arcticicestudio/nord/issues/46 instead.
