### ISSUE TITLE
Emacs menu area 'not covered' by theme

### ISSUE THREAD

**Issue by eddelbuettel** [arcticicestudio/nord-emacs#84]
Big nord fan here.  Just upgraded a machine from Ubuntu 19.04 to 19.10, and now the menu bar appears to be uncovered by the theme:

![image](https://user-images.githubusercontent.com/673121/70931690-9c701700-1ffd-11ea-8009-bab63c29ead8.png)

Seemingly the 19.04 release has Emacs 26.1 whereas this now happens with 26.3.  Anybody know how I could overcome this?

**Comment by arcticicestudio** [comment]
Hi @eddelbuettel, nice to see you like Nord :smile: 
I guess you're running Emacs in GUI mode. I have to admit that I've never really paid attention to the menu bar color. My first guess would be that it is part of the window so the running window manager (latest Ubuntu version using GNOME so it's [Mutter][]) and the style of based on the used GTK3 theme, but I could also be completely wrong.

I'll create VirtualBox to test the menu with Ubuntu 19.04.

[mutter]: https://gitlab.gnome.org/GNOME/mutter

**Comment by eddelbuettel** [comment]
I do :)  In gnome-terminal / tmux and Emacs.  I later realized that this _may_ have something to do with Ubuntu too.  Case in point is that their default them also bit the Atom editor where the menu bar is/was unavailable / invisible for at least a year (and two releases) if not more -- can probably find links.

And while I am a loooooong time x11 user I have no idea how to find the resource name of that section.  A quick poke at editres revealed nothing.   So whatever you can come up with I'd gratefully use (and test and re-test ...).

**Comment by arcticicestudio** [comment]
A quick scan of the changelog for version 26.1 to 26.3 includes [a change that might be related to your problem][q]:

> Building Emacs with the '--with-xwidgets' option now requires WebKit2.
To build Emacs with xwidgets support, you will need to install the
webkit2gtk-4.0 package; version 2.12 or later is required.
(This change was actually made in Emacs 26.1, but was not called out
in its NEWS.)

I don't know for which elements [WebKitGTK][] is used by Emacs, but maybe it's used to style some GTK3 components. The package is [available from the official Ubuntu repositories][p].

[q]: https://github.com/emacs-mirror/emacs/blob/master/etc/NEWS.26#L33-L37
[webkitgtk]: https://webkitgtk.org
[p]: https://packages.ubuntu.com/eoan/libwebkit2gtk-4.0-37

**Comment by eddelbuettel** [comment]
Could well be--I just use the default binary.  On a lurk, I install emacs-lucid, and it does of course not have the problem.  (But makes me feel it is 1998 all over again, but that is a different issue ;-) )

**Comment by eddelbuettel** [comment]
Actually, and one thing I just noticed -- it is also the same under the older (26.1) Emacs _when running in console mode_ for example in tmux.  Screenshot from Emacs/Magit on an (older) checkout of Nord:

![image](https://user-images.githubusercontent.com/673121/71002495-0099e600-20a5-11ea-81b2-b438198f29fb.png)

So how do we get to that menu line?

**Comment by eddelbuettel** [comment]
I think it may not be you but "them", _i.e._ an Ubuntu theme issue:  https://www.linuxuprising.com/2019/10/how-to-get-dark-gnome-shell-menus-and.html

**Comment by eddelbuettel** [comment]
I think I will close this. It very appears "by design" in Ubuntu and _e.g._ goes away when selecting a dark theme via the `Tweak` tool.  And by now ... I have gotten used to it :)    All still good with Nord just about everywhere:  gnome-shell, tmux/byobu, emacs, ...
