### ISSUE TITLE
Support dired

### ISSUE THREAD

**Issue by noaccOS** [arcticicestudio/nord-emacs#97]
![image](https://user-images.githubusercontent.com/24324352/79047291-04ceae00-7c16-11ea-923a-0efcf4f3307a.png)

At the moment dired is not really themed correctly

**Comment by arcticicestudio** [comment]
Hi @noaccOS :wave:, thanks for your contribution :+1:

I've added it to the backlog, but everyone can feel free to submit a PR 😄

**Comment by TRSx80** [comment]
@noaccOS,

Why does your `dired` buffer look so strange colors? Mine looks nothing like that...

Mine looks very consistent with Nord theme:

![2020-04-16_065016_screenshot](https://user-images.githubusercontent.com/25938297/79448069-cdae2300-7fae-11ea-8c61-f6a32ab47728.png)

**Comment by noaccOS** [comment]
@TRSx80 I don't know, I have set nord as the Doom Emacs theme (I'm using that distribution) and it was the normal GUI application, not the daemon in which I know the theme has problems

**Comment by TRSx80** [comment]
You have any old themes set in Custom? Go to menu (or F10) -> Options -> Customize Emacs -> Custom Themes and tell me if you see anything checked. If so, un-check it.

How are you loading `nord-theme`?

**Comment by noaccOS** [comment]
@TRSx80 Nope, I only have nord

![image](https://user-images.githubusercontent.com/24324352/79451035-264ce280-7fe6-11ea-9509-24f28504ae5c.png)

I'm setting the theme with `(setq doom-theme 'nord)` in `~/.doom.d/config.el`

**Comment by articuluxe** [comment]
Are you using nord-theme or doom-nord-theme?

**Comment by noaccOS** [comment]
@articuluxe nord-theme
It seems setting the theme to doom-nord fixes dired, it might be an issue with doom emacs
Thank you for your support
